// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    switch (false) {
      case typeof window === 'undefined':
        return require('./window');
      case typeof self === 'undefined':
        return require('./worker');
      default:
        throw new Error('uknown context');
    }
  })();

}).call(this);

//# sourceMappingURL=index.js.map
