// Generated by CoffeeScript 1.10.0
(function() {
  var Wurker,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Wurker = require('./wurker');

  module.exports = (function(superClass) {
    extend(_Class, superClass);

    _Class.context = 'worker';

    function _Class() {
      this.context = self;
      _Class.__super__.constructor.apply(this, arguments);
    }

    return _Class;

  })(Wurker);

}).call(this);

//# sourceMappingURL=worker.js.map
